const API='http://127.0.0.1:5000';
let selectedFiles=[];
let observations=new Map();
let selectedNo=null;
let map=null, mapLayers=[], replayTimer=null, streetLayer=null, satelliteLayer=null;
const $=id=>document.getElementById(id);
const esc=x=>String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function setGlobal(msg, kind=''){const box=$('globalStatus'); if(box) box.className=kind==='error'?'notice danger':'notice'; if(box) box.innerHTML=msg;}
function pipeline(step){document.querySelectorAll('[data-step]').forEach(x=>{const n=Number(x.dataset.step);x.classList.toggle('active',n<=step);x.classList.toggle('completed',n<step)});}
function showSection(id){document.querySelectorAll('.page-section').forEach(s=>s.classList.remove('active-section'));$(id)?.classList.add('active-section');document.querySelectorAll('.nav-item').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.nav-item').forEach(b=>{if((b.getAttribute('onclick')||'').includes(`'${id}'`))b.classList.add('active')});window.scrollTo({top:0,behavior:'smooth'});if(id==='investigation'&&map)setTimeout(()=>map.invalidateSize(),250)}

async function health(){const r=await fetch(API+'/health');if(!r.ok)throw Error('MarineGuard backend is not reachable.');return r.json()}

$('imageInput').addEventListener('change',()=>{selectedFiles=[...$('imageInput').files];renderSelectedFiles();});
function renderSelectedFiles(){const box=$('imagePreview');if(!selectedFiles.length){box.innerHTML='';return}box.innerHTML=`<div class="successbox"><b>🛰️ ${selectedFiles.length} satellite frame(s) selected</b><div class="mini">Each frame will become its own immutable observation.</div><div class="uploaded-grid">${selectedFiles.map((f,i)=>`<div class="uploaded-card"><img src="${URL.createObjectURL(f)}"><div class="meta"><strong>Observation ${String(i+1).padStart(2,'0')}</strong><span class="mini">${esc(f.name)}</span><span class="badge">Independent investigation</span></div></div>`).join('')}</div></div>`}

async function resetSession(){try{await fetch(API+'/session/reset',{method:'POST'});}catch(e){} observations.clear();selectedNo=null;renderObservationList();renderReportList();$('report').innerHTML='<div class="empty-state">Select a report to view its details.</div>';setGlobal('New investigation session ready.');updateDashboard();}

async function uploadAIS(){const f=$('aisInput').files[0];if(!f){$('aisStatus').innerHTML='⚠️ Choose an AccessAIS CSV first.';return}$('aisStatus').innerHTML='🔄 Parsing AccessAIS historical AIS points…';try{const fd=new FormData();fd.append('ais',f);const r=await fetch(API+'/ais/upload',{method:'POST',body:fd});const d=await r.json();if(!r.ok||!d.success)throw Error(d.message||'AccessAIS upload failed');$('aisStatus').innerHTML=`✅ <b>${d.rows_loaded.toLocaleString()}</b> AccessAIS points loaded across <b>${d.vessels}</b> vessels.`;for(const [n,o] of observations){const rr=await fetch(API+`/report?observation=${n}`);const dd=await rr.json();if(dd.success)observations.set(n,dd.report)}renderObservationList();if(selectedNo)selectObservation(selectedNo)}catch(e){$('aisStatus').innerHTML='❌ '+esc(e.message)}}

async function runInvestigation(){if(!selectedFiles.length){setGlobal('⚠️ Select satellite images first.','error');showSection('satellite');return}try{await health()}catch(e){setGlobal('❌ Failed to fetch backend. Keep server.py running and use http://127.0.0.1:5000','error');return}await resetSession();$('runBtn').disabled=true;for(let i=0;i<selectedFiles.length;i++){await processOne(selectedFiles[i],i+1)}$('runBtn').disabled=false;pipeline(5);setGlobal(`✅ Complete — ${selectedFiles.length} independent observation(s) saved.`);renderObservationList();renderReportList();showSection('reports');}

async function processOne(file,n){pipeline(1);setGlobal(`Observation ${String(n).padStart(2,'0')} — satellite ingestion`);$('analysisResult').innerHTML=`🔄 <b>Observation ${String(n).padStart(2,'0')}</b> — ${esc(file.name)}<br><span class="mini">Satellite → AI/Slick → Origin → AccessAIS → Report</span>`;const fd=new FormData();fd.append('image',file);fd.append('observation_number',n);try{pipeline(2);const r=await fetch(API+'/analyze',{method:'POST',body:fd});const d=await r.json();if(!r.ok||!d.success)throw Error(d.message||'Analysis failed');d.observation._previewUrl = URL.createObjectURL(file); observations.set(n,d.observation);selectedNo=n;pipeline(3);renderObservationList();renderReportList();selectObservation(n);pipeline(4);await new Promise(res=>setTimeout(res,100));pipeline(5);$('analysisResult').innerHTML=`<div class="successbox"><b>✅ ${d.observation.display_label} complete</b><div class="metric-row"><span class="metric">Slick ${d.observation.slick_score}%</span><span class="metric">AI ${d.observation.ai_assessment.score}%</span><span class="metric">Origin ${d.observation.reconstruction.origin_confidence}%</span><span class="metric">AccessAIS ${d.observation.ais_candidates.length}</span></div></div>`}catch(e){$('analysisResult').innerHTML=`<div class="notice danger">❌ ${esc(e.message)}</div>`}}

function renderObservationList(){const box=$('observationList');const arr=[...observations.values()].sort((a,b)=>a.sequence-b.sequence);if(!arr.length){box.innerHTML='<div class="empty-state">No observations yet.</div>';return}box.innerHTML=arr.map(o=>`<div class="obs-card"><img class="obs-thumb" src="${o._previewUrl||''}" alt="${esc(o.display_label)} satellite frame"><div><strong>${esc(o.display_label)} <span class="mini">${esc(o.observation_id)}</span></strong><div class="mini">Source: ${esc(o.source_filename)}</div><div class="metric-row"><span class="metric">Slick ${o.slick_score}%</span><span class="metric">${o.estimated_area_km2} km²</span><span class="metric">Origin ${o.reconstruction.origin_confidence}%</span><span class="metric">${o.ais_candidates.length} AIS tracks</span></div></div><div class="obs-actions"><button onclick="viewObservation(${o.sequence})">View</button></div></div>`).join('');}

function renderReportList(){const box=$('reportList');const arr=[...observations.values()].sort((a,b)=>a.sequence-b.sequence);if(!arr.length){box.innerHTML='<div class="empty-state">No reports yet.</div>';return}box.innerHTML=arr.map(o=>`<div class="obs-card"><div style="display:flex;align-items:center;justify-content:center;font-size:32px">📄</div><div><strong>${esc(o.display_label)} — ${esc(o.observation_id)}</strong><div class="mini">${esc(o.source_filename)}</div><div class="metric-row"><span class="metric">Slick ${o.slick_score}%</span><span class="metric">Origin ${o.reconstruction.origin_confidence}%</span><span class="metric">${o.ais_candidates.length} AccessAIS candidates</span></div></div><div class="obs-actions"><button onclick="viewReport(${o.sequence})">View Report</button></div></div>`).join('');}

function viewObservation(n){showSection('investigation');setTimeout(()=>selectObservation(n),220);}
function selectObservation(n){const o=observations.get(n);if(!o)return;selectedNo=n;$('selectedInvestigationTitle').innerHTML=`<b>${esc(o.display_label)}</b> · ${esc(o.source_filename)} · ${esc(o.observation_id)}`;$('mapTitle').innerText=`${o.display_label} — Incident Map`;$('mapLabel').innerText=`${o.display_label} · ${o.observation_id}`;renderMap(o);renderInvestigationDetails(o);updateDashboard();}

function initMap(){if(map)return;map=L.map('map').setView([15.4,73.8],9);streetLayer=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19});satelliteLayer=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{attribution:'© Esri, Maxar, Earthstar Geographics, and the GIS User Community',maxZoom:19});streetLayer.addTo(map);L.control.layers({'Street Map':streetLayer,'Satellite View':satelliteLayer},{},{collapsed:false}).addTo(map);}
function clearMap(){mapLayers.forEach(x=>{try{map.removeLayer(x)}catch(e){}});mapLayers=[]}
function renderMap(o){initMap();clearMap();const origin=[o.reconstruction.origin_lat,o.reconstruction.origin_lon],slick=[o.latitude,o.longitude];const p=L.polyline(o.reconstruction.path,{weight:5,dashArray:'8 7'}).addTo(map);const om=L.circleMarker(origin,{radius:9,color:'#ff4d5a',fillColor:'#ff4d5a',fillOpacity:.9}).bindPopup(`<b>🔴 ${esc(o.display_label)} origin</b><br>${o.reconstruction.origin_lat}°N, ${o.reconstruction.origin_lon}°E`).addTo(map);const sm=L.circleMarker(slick,{radius:10,color:'#f2a900',fillColor:'#f2a900',fillOpacity:.6}).bindPopup(`<b>🛢️ Observed slick</b><br>Score ${o.slick_score}%`).addTo(map);mapLayers.push(p,om,sm);o.ais_candidates.forEach((v,i)=>{const m=L.circleMarker([v.lat,v.lon],{radius:i<3?7:5,color:'#48aee8',fillColor:'#48aee8',fillOpacity:.85}).bindPopup(`<b>🚢 ${esc(v.VesselName)}</b><br>AccessAIS score: ${v.score}%<br>MMSI: ${esc(v.MMSI)}<br>Distance: ${v.distance_km} km`);m.addTo(map);mapLayers.push(m);if(v.track.length>1){const tr=v.track.map(x=>[x.LAT,x.LON]);const line=L.polyline(tr,{weight:i<3?3:2,opacity:.45}).addTo(map);mapLayers.push(line)}});map.fitBounds(L.latLngBounds([origin,slick,...o.ais_candidates.slice(0,10).map(v=>[v.lat,v.lon])]),{padding:[30,30]});}

function renderInvestigationDetails(o){$('investigationDetails').innerHTML=`<div class="successbox"><b>${esc(o.display_label)} · ${esc(o.observation_id)}</b><div class="mini">Source image: ${esc(o.source_filename)}</div><div class="metric-row"><span class="metric">📍 ${esc(o.location)}</span><span class="metric">🛢️ Slick ${o.slick_score}%</span><span class="metric">🤖 AI ${o.ai_assessment.score}%</span><span class="metric">🎯 Origin ${o.reconstruction.origin_confidence}%</span><span class="metric">🚢 ${o.ais_candidates.length} AccessAIS tracks</span></div></div><div class="report-section"><b>Automatic geolocation</b><p>${esc(o.location)} · ${esc(o.location_method)}</p></div><div class="report-section"><b>Reconstruction</b><p>Origin: <b>${o.reconstruction.origin_lat}°N, ${o.reconstruction.origin_lon}°E</b><br>Transport: ${o.reconstruction.transport_distance_km} km · Lookback: ${o.reconstruction.lookback_hours} h · Uncertainty: ±${o.reconstruction.uncertainty_km} km</p></div><div class="report-section"><b>Top AccessAIS candidates</b>${o.ais_candidates.slice(0,8).map((v,i)=>`<p>${i+1}. <b>${esc(v.VesselName)}</b> · ${v.score}% · ${v.distance_km} km · MMSI ${esc(v.MMSI)} · ${v.track.length} points</p>`).join('')||'<p>No candidates. Load the correct AccessAIS CSV.</p>'}</div>`}

function viewReport(n){const o=observations.get(n);if(!o)return;selectedNo=n;selectObservation(n);$('report').innerHTML=`<div class="report-titlebar"><div><h3>📄 ${esc(o.display_label)} — ${esc(o.observation_id)}</h3><div class="mini">Source image: ${esc(o.source_filename)}</div></div></div><div class="report-section"><b>Satellite + AI</b><p>AI assessment: <b>${esc(o.ai_assessment.label)}</b> · ${o.ai_assessment.score}%<br>Slick score: <b>${o.slick_score}%</b> · Area: <b>${o.estimated_area_km2} km²</b> · Overall confidence: <b>${o.confidence}%</b></p></div><div class="report-section"><b>Automatic Location</b><p>${esc(o.location)} · ${esc(o.location_method)}<br>Observation time: ${esc(o.observation_time)}</p></div><div class="report-section"><b>Incident Reconstruction</b><p>Origin: <b>${o.reconstruction.origin_lat}°N, ${o.reconstruction.origin_lon}°E</b> · ${o.reconstruction.origin_confidence}% confidence<br>Transport: ${o.reconstruction.transport_distance_km} km · Lookback: ${o.reconstruction.lookback_hours} h · Uncertainty: ±${o.reconstruction.uncertainty_km} km</p></div><div class="report-section"><b>AccessAIS Multi-Vessel Intelligence</b><p>Source: ${esc(o.ais_source)}</p><table class="report-table"><thead><tr><th>#</th><th>Vessel</th><th>MMSI</th><th>Score</th><th>Distance</th><th>Time</th><th>Heading</th><th>Track</th></tr></thead><tbody>${o.ais_candidates.map((v,i)=>`<tr><td>${i+1}</td><td>${esc(v.VesselName)}</td><td>${esc(v.MMSI)}</td><td>${v.score}%</td><td>${v.distance_km} km</td><td>${v.time_match}%</td><td>${v.heading_match}%</td><td>${v.track.length}</td></tr>`).join('')||'<tr><td colspan="8">No matching AccessAIS tracks.</td></tr>'}</tbody></table></div><div class="report-section"><b>Evidence Chain</b>${o.evidence.map(e=>`<p>✓ <b>${esc(e.stage)}:</b> ${esc(e.finding)} — ${esc(e.detail)}</p>`).join('')}</div>`;showSection('reports');}

function requireSelected(){const o=observations.get(selectedNo);if(!o){setGlobal('Select an observation first.','error');showSection('satellite');return null}return o;}
function actionStatus(msg){const el=$('investigationActionStatus');if(el)el.innerHTML=msg;setGlobal(msg);}
function reconstructOrigin(){const o=requireSelected();if(!o)return;actionStatus(`🔴 <b>Origin reconstructed</b> — ${esc(o.display_label)}<br><span class="mini">Estimated origin: ${o.reconstruction.origin_lat}°N, ${o.reconstruction.origin_lon}°E · ${o.reconstruction.origin_confidence}% confidence · Lookback ${o.reconstruction.lookback_hours} h</span>`);renderMap(o);renderInvestigationDetails(o);}
function correlateVessels(){const o=requireSelected();if(!o)return;actionStatus(`🚢 <b>Vessel correlation complete</b> — ${o.ais_candidates.length} AccessAIS candidate track(s) correlated with ${esc(o.display_label)}.`);renderMap(o);renderInvestigationDetails(o);}
function generateEvidence(){const o=requireSelected();if(!o)return;selectedNo=o.sequence;viewReport(o.sequence);actionStatus(`📄 <b>Evidence generated</b> — ${esc(o.display_label)} report is ready in Investigation Report.`);}

function replaySelected(){const o=observations.get(selectedNo);if(!o){setGlobal('Select an observation first.','error');return}showSection('investigation');initMap();clearMap();let i=0;const path=o.reconstruction.path;setGlobal(`▶ Replaying ${o.display_label} reconstruction…`);if(replayTimer)clearInterval(replayTimer);const origin=[o.reconstruction.origin_lat,o.reconstruction.origin_lon],slick=[o.latitude,o.longitude];const line=L.polyline([], {weight:5,dashArray:'8 7'}).addTo(map);const marker=L.circleMarker(path[0],{radius:8,color:'#ff4d5a',fillColor:'#ff4d5a',fillOpacity:.9}).addTo(map);mapLayers.push(line,marker);replayTimer=setInterval(()=>{if(i>=path.length){clearInterval(replayTimer);replayTimer=null;setGlobal(`✅ ${o.display_label} reconstruction replay complete.`);renderMap(o);return}line.addLatLng(path[i]);marker.setLatLng(path[i]);map.flyTo(path[i],10,{duration:.45});i++},650)}

async function startContinuous(){if(!selectedFiles.length){setGlobal('Select satellite images first.','error');return}try{await resetSession();for(let i=0;i<selectedFiles.length;i++){await processOne(selectedFiles[i],i+1);await new Promise(r=>setTimeout(r,500))}setGlobal(`✅ Sequential monitoring complete — ${selectedFiles.length} observations retained.`);renderReportList();showSection('reports')}catch(e){setGlobal('❌ '+e.message,'error')}}

function updateDashboard(){const arr=[...observations.values()];$('dashReports').innerText=arr.length;if(!arr.length){$('dashSlick').innerText='—';$('dashVessels').innerText='0';$('dashOrigin').innerText='—';return}const o=observations.get(selectedNo)||arr[arr.length-1];$('dashSlick').innerHTML=`${o.slick_score}%<br><small>${o.estimated_area_km2} km²</small>`;$('dashVessels').innerText=o.ais_candidates.length;$('dashOrigin').innerText=`${o.reconstruction.origin_confidence}%`}

renderObservationList();renderReportList();updateDashboard();pipeline(0);
